Implementation of Frame Allocator and Subblock Allocator
KidneyOS/KidneyOS pull request #104
Opened 2024-10-31 02:36 UTC by PrimeAce123

This pull request contains a working implementation of the system Subblock Allocator and Frame Allocator (including Dummy Allocator to setup the coremap). They have passed simply tests (which can be found in mem/mod.rs) but further testing should be done to ensure correctness of internal data structures. 

As of currently, the following features have not been implemented yet in the Subblock Allocator
1. Allocations for sizes larger than one frame will cause an AllocError (this means that the call to setup the page tables will fail because it requires a size larger than one frame)
2. We do not do frame reclamation after all the subblocks in a certain frame have been freed
3. 'deinit' for both the frame and subblock allocator have not been implemented yet

2024-11-07 04:44 UTC, tonyhu-x requested changes
Shouldn't be merged yet until we implement larger-than-one-block allocations.

2024-11-07 04:48 UTC, PrimeAce123 commented on kernel/src/mem/frame_allocator.rs
> +}
I got a warning from Rust about how all the enums ended with the same word; I thought that it wouldn't make too much of a difference but now that I think about it, it is definitely more clear to use the full name i.e. NextFit, FirstFit, BestFit

2024-11-07 04:49 UTC, PrimeAce123 commented on kernel/src/mem/mod.rs
>  }
I will definitely refactor that

2024-11-08 01:51 UTC, PrimeAce123 commented on kernel/src/mem/subblock_allocator.rs
> +                }
Can you elaborate a bit on what you mean by pointer arithmetic? Are you referring to to just avoiding the cast to usize for the start_of_subblock_ptr part?

2024-11-08 01:51 UTC, PrimeAce123 commented on kernel/src/mem/subblock_allocator.rs
> +}
Sounds good

2024-11-08 01:54 UTC, PrimeAce123 commented on kernel/src/mem/mod.rs
> +            TOTAL_NUM_ALLOCATIONS.store(new_total_allocs, Ordering::Relaxed);
I think Jack mentioned that we should try to keep allocation statistics (such as how many allocations were made, total size of allocations, etc). I think later we will need these metrics, but for now, I think I can probably replace this with a bool like you suggested; we can add the metrics in a later pull request.

2024-11-08 01:54 UTC, PrimeAce123 commented on kernel/src/mem/subblock_allocator.rs
> +                };
Sounds good

2024-11-08 01:55 UTC, PrimeAce123 commented on kernel/src/mem/subblock_allocator.rs
> +            println!(
Sounds good

2024-11-11 00:34 UTC, PrimeAce123 commented
> Shouldn't be merged yet until we implement larger-than-one-block allocations.

Implemented this feature in the latest commit

In terms of testing, I did some playing around and I'm pretty sure the current tests in "mem/mod.rs" don't use the allocator we have written; it uses some other global allocator (I think its the default Rust one but I'm not sure). This is something we should address with the other groups to try and make sure all their tests use our allocator (as a temporarily solution, I've been running the tests in the main function and seeing if they pass)

2024-11-11 21:03 UTC, tonyhu-x commented
> > Shouldn't be merged yet until we implement larger-than-one-block allocations.
> 
> Implemented this feature in the latest commit
> 
> In terms of testing, I did some playing around and I'm pretty sure the current tests in "mem/mod.rs" don't use the allocator we have written; it uses some other global allocator (I think its the default Rust one but I'm not sure). This is something we should address with the other groups to try and make sure all their tests use our allocator (as a temporarily solution, I've been running the tests in the main function and seeing if they pass)

The tests don't run our allocator, and they wouldn't be able to. The tests themselves run on the host, i.e. whichever OS we're writing our code in. Therefore, we can't directly initialize the `KernelAllocator` the same way we do when the code runs on QEMU. Even if we could, since the subblock allocator itself is not a global allocator, in our unit tests we should call its functions directly. Actually doing it is a bit difficult though, since the subblock allocator depends on `FrameAllocator`, so we can either initialize a `FrameAllocator`, giving it a pre-allocated pool of memory, or pass a fake `FrameAllocator` to our subblock allocator.

2024-11-11 21:06 UTC, tonyhu-x commented on kernel/src/mem/mod.rs
> +mod test {
`mod tests` may be more conventional.

2024-11-11 22:55 UTC, tonyhu-x commented
Before we merge the code, we should also remove the `println` statements.

2024-11-12 05:30 UTC, PrimeAce123 commented on kernel/src/mem/frame_allocator.rs
> +    fn dealloc(&mut self, ptr_to_dealloc: NonNull<u8>) -> usize {
Sounds good

2024-11-12 05:30 UTC, PrimeAce123 commented on kernel/src/mem/mod.rs
> +mod test {
Sounds good

2024-11-13 05:04 UTC, tonyhu-x commented on kernel/src/mem/frame_allocator.rs
> +            placement_algorithm: next_fit,
I just realized that there is no way for the `KernelAllocator` to provide the placement algorithm. Instead, the choice is fixed here. We should change it. Further, I don't see a reason why the `FrameAllocator` trait has to define a constructor function. It just needs the signatures for `alloc` and `dealloc`. The constructor should be defined in its own `impl` block.

2024-11-13 05:04 UTC, tonyhu-x commented on kernel/src/mem/frame_allocator.rs
> +    fn new_in(start: NonNull<u8>, core_map: Box<[CoreMapEntry]>) -> Self {
I think we should rename the constructor to `new`. It seems that the standard library uses `new_in` as a conventional name for constructors that take a custom allocator. This is not what happens here.

2024-11-13 14:12 UTC, PrimeAce123 commented on kernel/src/mem/frame_allocator.rs
> +            placement_algorithm: next_fit,
Got it; that does make a lot more sense

2024-11-13 14:13 UTC, PrimeAce123 commented on kernel/src/mem/frame_allocator.rs
> +    fn new_in(start: NonNull<u8>, core_map: Box<[CoreMapEntry]>) -> Self {
Sounds good

2024-11-16 22:26 UTC, tonyhu-x commented
Refactored the code a bit more (read the commit body for details). Let me know what you think.

2024-11-28 04:20 UTC, tonyhu-x approved these changes

2024-11-28 04:59 UTC, PrimeAce123 commented
Before merging, CoreMapEntry in frame_allocator.rs needs to be refactored to not use bitbybit but instead bitfield (since bitbybit dependency is removed)

2024-11-28 20:37 UTC, merged