Add segment validation for each program header.
KidneyOS/KidneyOS pull request #20
Opened 2024-03-25 21:51 UTC by serenayu11

The function validate_segment() is added, it is responsible for verifying that a segment described by a program header in an ELF file is valid and can be safely loaded into memory for execution.

2024-03-29 03:22 UTC, serenayu11 commented
Thanks Ray for making the change :)

2024-04-01 17:40 UTC, mtoohey31 requested changes
Thanks for making these changes! Looks like we're on the right track, I just have a couple questions about some of the checks.

2024-04-01 17:40 UTC, mtoohey31 commented on kernel/src/user_program/elf_loader.rs
> +        if (ph.p_type == SegmentType::Load as u32) && validate_segment(ph, elf_data).is_ok() {
Using `is_ok` here still just skips the segment if validation fails. I'd recommend something like this:

```diff
diff --git a/kernel/src/user_program/elf_loader.rs b/kernel/src/user_program/elf_loader.rs
index dcd9f2e..b8343f1 100644
--- a/kernel/src/user_program/elf_loader.rs
+++ b/kernel/src/user_program/elf_loader.rs
@@ -56,6 +56,7 @@ pub enum ElfError {
     UnsupportedVersion,
     UnsupportedType,
     UnsupportedMachine,
+    SegmentError(ElfSegmentError),
     // Additional error types as needed
 }
 
@@ -193,7 +194,9 @@ fn load_elf(elf_data: &[u8]) -> Result<(), ElfError> {
                 .cast::<Elf32Phdr>()
         };
 
-        if (ph.p_type == SegmentType::Load as u32) && validate_segment(ph, elf_data).is_ok() {
+        if ph.p_type == SegmentType::Load as u32 {
+            validate_segment(ph, elf_data).map_err(ElfError::SegmentError)?;
+
             let vm_start = ph.p_vaddr as usize;
             let vm_end = vm_start + ph.p_memsz as usize;
```

2024-04-01 17:40 UTC, mtoohey31 commented on kernel/src/user_program/elf_loader.rs
> +    }
I'm not clear on why we need to ensure that this is the case. According to the [ELF spec](https://refspecs.linuxfoundation.org/elf/elf.pdf), `p_offset` is the offset within `file_data` of the data to be mapped at the `p_vaddr` virtual address, so I don't see why they'd have to be the same. Is there a reason I've missed?

2024-04-01 17:40 UTC, mtoohey31 commented on kernel/src/user_program/elf_loader.rs
> +    if phdr.p_offset as usize > file_data.len() {
```suggestion
    // The range must be within FILE.
    if (phdr.p_offset + phdr.p_filesz) as usize > file_data.len() {
```

I think we also need to ensure that `p_filesz` doesn't cause the end of the range to extend beyond the end of the data.

2024-04-01 17:40 UTC, mtoohey31 commented on kernel/src/user_program/elf_loader.rs
> +    }
The [ELF spec](https://refspecs.linuxfoundation.org/elf/elf.pdf) says on page 2-2 that `p_memsz` "may be zero".

2024-04-01 17:40 UTC, mtoohey31 commented on kernel/src/user_program/elf_loader.rs
> +    }
This check appears to rely on C-like integer overflow wrapping behaviour. In Rust, the program will panic on integer overflow in debug builds. I'd suggest removing this check, and swapping the one above for something like:

```rust
    if !is_user_vaddr(
        phdr.p_vaddr
            .checked_add(phdr.p_memsz)
            .ok_or(ElfSegmentError::VMRegionWrapAround)?
            .saturating_sub(1) as *const (),
    ) {
        return Err(ElfSegmentError::VMRegionOutOfRange);
    }
```

(The `.saturating_sub(1)` will also handle the off-by-one that I mentioned in the previous comment. If it turns out I'm wrong about there being an issue there though you can just remove that method call and the rest should work.)

2024-04-01 17:40 UTC, mtoohey31 commented on kernel/src/user_program/elf_loader.rs
> +    if !is_user_vaddr((phdr.p_vaddr as usize + phdr.p_memsz as usize) as *const ()) {
I may be wrong, but I suspect there is an off-by-one error in this check. Since `p_vaddr` is the start address and `p_memsz` is the length, `p_vaddr + p_memsz` is the end of the non-inclusive mapped range, meaning it isn't mapped itself, right? I think we only need to check that `p_vaddr + p_memsz - 1` isn't a user virtual address. You can do this using `.saturating_sub(1)` to ensure you don't overflow if both are zero for some reason.

2024-04-01 22:04 UTC, serenayu11 commented on kernel/src/user_program/elf_loader.rs
> +    }
https://stackoverflow.com/questions/52533193/how-to-understand-the-difference-between-offset-and-viraddr-in-program-headers-i
From this discussion they commented that "What is guaranteed is that .p_offset % pagesize == .p_vaddr % pagesize (otherwise mmap will become impossible)."

2024-04-01 22:11 UTC, serenayu11 commented on kernel/src/user_program/elf_loader.rs
> +    }
Yes, but, I think if this is the case we don't need to load this segment into memory?

2024-04-01 22:11 UTC, serenayu11 commented on kernel/src/user_program/elf_loader.rs
> +    }
I see!

2024-04-01 22:13 UTC, serenayu11 commented on kernel/src/user_program/elf_loader.rs
> +    }
Then this should not be treated as an error, and continue to load rest of the segments

2024-04-01 22:30 UTC, mtoohey31 commented on kernel/src/user_program/elf_loader.rs
> +    }
The condition in your comment looks about right, but the one in the code here is a different one. If we want to check for the condition in the comment then I think we should use something like: `p_align == 0 || p_align == 1 || (p_offset % p_align == p_vaddr % p_align)` (see the end of page 2-2 of the ELF spec for explanation of the first two or cases).

2024-04-01 22:43 UTC, mtoohey31 commented on kernel/src/user_program/elf_loader.rs
> +    }
Yeah this shouldn't be treated as an error. Your call on how you want to change things, there are two possibilities I can think of:
1. Change the return type to `Result<bool, ...>` and use the boolean to indicate whether to skip the segment. If you decided to go with this, then this check should become the last one, cause we should produce an error if there are any other issues with the segment aside from it being 0-length.
2. Just remove the check here and leave it to the code that processes the segments to detect this.

2024-04-01 23:16 UTC, serenayu11 commented on kernel/src/user_program/elf_loader.rs
> +        if (ph.p_type == SegmentType::Load as u32) && validate_segment(ph, elf_data).is_ok() {
Resolved in commit 837ff0292a6c0e5e99fc95455e29f5e93a3a1eb9

2024-04-01 23:16 UTC, serenayu11 commented on kernel/src/user_program/elf_loader.rs
> +    }
Resolved in commit 1219e1f728a9c9d5632ff6a28a6f698bffef7fe2

2024-04-01 23:17 UTC, serenayu11 commented on kernel/src/user_program/elf_loader.rs
> +    if !is_user_vaddr((phdr.p_vaddr as usize + phdr.p_memsz as usize) as *const ()) {
I think you are right, I don't know why Pintos doesn't consider this.

2024-04-01 23:24 UTC, serenayu11 commented on kernel/src/user_program/elf_loader.rs
> +    if !is_user_vaddr((phdr.p_vaddr as usize + phdr.p_memsz as usize) as *const ()) {
Resolved in commit 84694b6c46f2b614d8386ef1b017df08a9335dbc

2024-04-01 23:30 UTC, serenayu11 commented on kernel/src/user_program/elf_loader.rs
> +    }
Resolved in commit 709bf1472fddc01a89b95cd5acbde9c468000743

2024-04-02 00:04 UTC, serenayu11 commented on kernel/src/user_program/elf_loader.rs
> +    if phdr.p_offset as usize > file_data.len() {
Changed in commit e05b3a76f46eedd171bb8c2bba05a9b56ab9b4dc, could you check if it is good? thanks.

2024-04-02 00:12 UTC, serenayu11 commented on kernel/src/user_program/elf_loader.rs
> +    if phdr.p_offset as usize > file_data.len() {
I am thinking to change the naming of ELFSegmentError:VmRegionWrapAround to ELFSegmentError:SegmentOverflow, do you think this would be more accurate?

2024-04-02 00:18 UTC, serenayu11 commented on kernel/src/user_program/elf_loader.rs
> +    }
I thought both calculations were used to ensure that p_offset and p_vaddr are aligned to the same position within a page? Just one using bitwise operation and one using %? Sorry, correct me if I am wrong.

2024-04-02 03:34 UTC, mtoohey31 commented on kernel/src/user_program/elf_loader.rs
> +    }
Oh I see, you're trying to use bitwise and instead of remainder? In that case I think `PGMASK` might be the wrong value to use, cause in binary its current value is `10111111111111111111111111111111`, which won't give us the value modulo the page size. And also, we shouldn't be basing this check on our own page size constant anyway, cause as the section of the ELF spec that I linked mentions, the only guarantee is that the two are equal modulo `p_align` if it's not 0 or 1, and `p_align` might not correspond to our page size.

2024-04-02 03:40 UTC, mtoohey31 commented on kernel/src/user_program/elf_loader.rs
> +    if phdr.p_offset as usize > file_data.len() {
Good idea with the use of `checked_add`. What about renaming `OffsetOutOfRange` to `ContentsOutOfRange` and using it both when overflow occurs, and when the result doesn't overflow but is bigger than `file_data.len()`?

2024-04-02 21:42 UTC, serenayu11 commented on kernel/src/user_program/elf_loader.rs
> +    if phdr.p_offset as usize > file_data.len() {
Sure

2024-04-02 21:46 UTC, serenayu11 commented on kernel/src/user_program/elf_loader.rs
> +    }
![image](https://github.com/KidneyOS/KidneyOS/assets/87595032/1d9086c3-a8a4-4084-90f6-a3d3f76fe22f)
Seems like it is 111111111111? Binary 4095

2024-04-02 22:05 UTC, serenayu11 commented on kernel/src/user_program/elf_loader.rs
> +    if phdr.p_offset as usize > file_data.len() {
Changed in commit 6abe23e161957c47adfdb991cf3bf299b4b74471

2024-04-03 00:08 UTC, mtoohey31 commented on kernel/src/user_program/elf_loader.rs
> +    }
Yes, but we can't be sure 4096 is the correct alignment to expect. As per the second half of my comment above, that's what `p_align` is for.

2024-04-03 00:31 UTC, mtoohey31 commented on kernel/src/user_program/elf_loader.rs
> +    if phdr.p_offset as usize > file_data.len() {
Oh sorry, forgot that `VMRegionWrapAround` was used below too. I don't think we should use `ContentsOutOfRange` there cause that doesn't really describe what went wrong in that case. Could we maybe leave `VMRegionWrapAround` or change it to `VMRegionOutOfRange` on line 164? Sorry about the back and forth...

2024-04-08 22:50 UTC, serenayu11 commented on kernel/src/user_program/elf_loader.rs
> +    if phdr.p_offset as usize > file_data.len() {
@mtoohey31 Changed in commit 90e94ff4881bca3ef9f629a8c70d286a75157db7 :)

2024-04-08 23:05 UTC, serenayu11 commented on kernel/src/user_program/elf_loader.rs
> +    }
@mtoohey31 Change in commit 8f52249656a850766760fd4d906555176832d658

2024-04-11 16:20 UTC, mtoohey31 approved these changes
Thanks for making the changes and adding comments. Looks good now!

2024-04-11 16:20 UTC, merged