Swap underlying bitfield crate
KidneyOS/KidneyOS pull request #67
Opened 2024-10-07 00:00 UTC by ff-zhang

We want to swap from the [bitbybit](https://crates.io/crates/bitbybit) crate over to the [bitfield](https://crates.io/crates/bitfield) crate.

2024-10-07 00:06 UTC, ff-zhang commented
@1whatleytay @pommicket The `bitfield!` macro is of the form:
```[rust]
bitfield! {
    struct Foo(u16);
    impl Debug;
    u16, bar, set_bar: 15, 0;
    ...
}
```
and generates a struct `Foo` with a getter `bar` and setter `set_bar`. For each setter, I want to write a function
```[rust]
fn with_bar(&mut self, value: T) {
    self.set_bar(value);
    self
}
```
so that we can chain multiple of them together. Do you know how to write a macro for this?

2024-10-07 01:34 UTC, pommicket commented
Hmm you can do
```rust
macro_rules! impl_with {
    ($type: ty, $setter: ident, $with: ident) => {
        fn $with(&mut self, value: $type) -> &mut Self {
            self.$setter(value);
            self
        }
    }
}

impl Foo {
    impl_with!(u16, set_bar, with_bar);
    // ... repeat for each field ...
}
```
But I think to do anything more automatic than this we'd need to modify the bitfield crate.

2024-10-10 04:12 UTC, 1whatleytay commented
We can probably avoid chaining altogether with https://docs.rs/bitfield/latest/bitfield/macro.bitfield_constructor.html?

2024-10-29 22:00 UTC, pommicket approved these changes
LGTM!

2024-10-29 22:00 UTC, pommicket commented on shared/src/bit_array.rs
> +            pub fn $name(&self) -> $t { self.0.get_range($low, $high) as $t }
These functions can be const right?

2024-10-29 22:00 UTC, pommicket commented on kernel/Cargo.toml
>  arbitrary-int = "1.2.7"
Looks like we can also remove `arbitrary-int` as a dependency now

2024-10-29 22:00 UTC, pommicket commented on shared/Cargo.toml
>  arbitrary-int = "1.2.7"
(We can also remove `arbitrary-int` here)

2024-10-31 03:35 UTC, pommicket commented on shared/src/bit_array.rs
> +                    BitArray((self.0 & !mask) | (value as $t & mask) << low)
Actually this should probably be `(value << low) & mask` here right? (Also, we might want to have an assertion that `((value << low) & !mask) == 0`)

2024-10-31 15:05 UTC, pommicket requested changes
(see above)

2024-10-31 20:17 UTC, ff-zhang commented on shared/src/bit_array.rs
> +                    BitArray((self.0 & !mask) | (value as $t & mask) << low)
Nice catch

2024-10-31 20:23 UTC, ff-zhang commented on shared/src/bit_array.rs
> +                    BitArray((self.0 & !mask) | (value as $t & mask) << low)
Nice catch!

2024-10-31 20:23 UTC, ff-zhang commented on shared/src/bit_array.rs
> +            pub fn $name(&self) -> $t { self.0.get_range($low, $high) as $t }
Those are no longer used and have been deleted.

2024-10-31 21:18 UTC, pommicket approved these changes
LGTM

2024-10-31 22:04 UTC, merged