First implementation of simple spinlock
KidneyOS/KidneyOS pull request #9
Opened 2024-03-05 00:47 UTC by serenayu11

This is the first implementation of a spinlock. 
Example of how to use the spinlock:
fn main() {
    
    // Initialize the SpinLock with some data.
    let counter = SpinLock::new(0);
    
    // Example of modifying the protected data.
    {
        let mut counter_guard = counter.lock();
        *counter_guard += 1;
        // Lock is automatically released when counter_guard goes out of scope.
    }

    // Example of reading the protected data.
    {
        let counter_guard = counter.lock();
        println!("Counter value is: {}", *counter_guard);
        // Lock is automatically released when counter_guard goes out of scope.
    }

    // Further processing...
}

2024-03-05 02:23 UTC, mtoohey31 requested changes
Looks great!

Just a few small suggestions. Also, I think we need to add a mod declaration to `lib.rs` before we can use this in other files:

```diff
diff --git a/src/lib.rs b/src/lib.rs
index 7a42933..0c3ce64 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -6,6 +6,7 @@ pub mod constants;
 pub mod macros;
 pub mod mem;
 pub mod serial;
+pub mod synch;
 pub mod video_memory;
 
 extern crate alloc;
```

2024-03-05 02:23 UTC, mtoohey31 commented on src/synch.rs
> +
```suggestion
```

Looks like this can safely be removed?

2024-03-05 02:23 UTC, mtoohey31 commented on src/synch.rs
> +
```suggestion
```

This also appears unused.

2024-03-05 02:23 UTC, mtoohey31 commented on src/synch.rs
> +        while self.lock.compare_exchange_weak(false, true, Ordering::Acquire, Ordering::Relaxed).is_err() {
```suggestion
        while self
            .lock
            .compare_exchange_weak(false, true, Ordering::Acquire, Ordering::Relaxed)
            .is_err()
        {
```

Sorry, I haven't gotten around to adding a rustfmt check as part of a GitHub action, but if you make this change then the file should match what rustfmt expects.

2024-03-05 12:36 UTC, serenayu11 commented on src/synch.rs
> +
I think we might need it in the future? So it can be used to indicate that a panic occurred while the lock was held.

2024-03-05 13:28 UTC, mtoohey31 commented on src/synch.rs
> +
I think mutex poisoning is mainly useful when you’re using multiple threads/cores, and one panics, but the others are still around to clean things up. My thought process is that since we’re using only a single core, if a panic occurs then there’s no chance of recovery. Maybe it would be possible to define some error recovery logic in the panic handler, but I think it would be extremely difficult to figure out how to restore the OS to a consistent state after a panic, so imo the best approach would be to do our best not to panic, and not worry about attempting to recover from panics. Does that seem reasonable?

2024-03-05 13:29 UTC, mtoohey31 commented
Thanks for making those changes! One other small nitpick I forgot to mention in the initial review, could we rename from synch to sync to be consistent with the naming of sync in core?

2024-03-15 04:24 UTC, mtoohey31 approved these changes
Looks great! I've just formatted things, and I think they're ready to be merged. Now I just have to figure out how to deal with the conflicts... will try to get that done soon!

2024-03-15 17:29 UTC, mtoohey31 commented
Ok, I think I managed to rebase everything without making too much of a mess, so I'm merging things.

2024-03-15 17:29 UTC, merged